name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install and build frontend
        working-directory: ./frontend
        env:
          VITE_API_URL: https://api.smashburgers.edinmesan.ba/api
        run: |
          npm install
          npm run build

      - name: Upload frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/dist/
          server-dir: /

      - name: Upload backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_BACKEND_SERVER }}
          username: ${{ secrets.FTP_BACKEND_USERNAME }}
          password: ${{ secrets.FTP_BACKEND_PASSWORD }}
          local-dir: ./backend/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
            **/.env.*
            **/uploads/**
            **/logs/**
            **/dist/**
            **/coverage/**
